# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import inference_pb2 as proto_dot_inference__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamInfer = channel.stream_stream(
                '/dcb.inference.InferenceService/StreamInfer',
                request_serializer=proto_dot_inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.BatchInfer = channel.unary_unary(
                '/dcb.inference.InferenceService/BatchInfer',
                request_serializer=proto_dot_inference__pb2.BatchRequest.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.BatchResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamInfer(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamInfer': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamInfer,
                    request_deserializer=proto_dot_inference__pb2.InferenceRequest.FromString,
                    response_serializer=proto_dot_inference__pb2.InferenceResponse.SerializeToString,
            ),
            'BatchInfer': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInfer,
                    request_deserializer=proto_dot_inference__pb2.BatchRequest.FromString,
                    response_serializer=proto_dot_inference__pb2.BatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dcb.inference.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dcb.inference.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamInfer(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/dcb.inference.InferenceService/StreamInfer',
            proto_dot_inference__pb2.InferenceRequest.SerializeToString,
            proto_dot_inference__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcb.inference.InferenceService/BatchInfer',
            proto_dot_inference__pb2.BatchRequest.SerializeToString,
            proto_dot_inference__pb2.BatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
